@IdCardApi_HostAddress = http://localhost:5242
@jwt = a.b.c
@apiKey = 12345

###

GET {{IdCardApi_HostAddress}}/_health
Authorization: Bearer {{jwt}}
X-API-Key: {{apiKey}}

###

GET {{IdCardApi_HostAddress}}/api/v1/WeatherForecast
Accept: application/json
X-API-Key: {{apiKey}}

###

POST {{IdCardApi_HostAddress}}/api/v1/WeatherForecast
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}
X-API-Key: {{apiKey}}
X-Trace-GUID: 35e42316-319b-4808-b045-96f4ab58d328
X-Idempotency-Token: sawyersawyer3

{
  "N": 3
}

###

GET {{IdCardApi_HostAddress}}/api/v1/weatherforecast/demo0?msg=foo
Authorization: Bearer {{jwt}}

###

GET {{IdCardApi_HostAddress}}/api/v1/weatherforecast/demo1?msg=bar
Authorization: Bearer {{jwt}}

###

GET {{IdCardApi_HostAddress}}/api/v1/weatherforecast/crash
